- hosts: backup-servers
  become: true
  vars_files:
    - group_vars/secrets.yml
  roles: 
  - common
  - extra-storage
  - backup

- hosts: common
  become: true
  vars_files:
    - group_vars/secrets.yml
  roles:
    - { role: common }

- hosts: extra-storage
  become: true
  roles:
    - { role: extra-storage }

- hosts: duckdns
  become: true
  vars_files:
    - group_vars/secrets.yml
  roles:
    - { role: duckdns }

- hosts: backup
  become: true
  vars_files:
    - group_vars/secrets.yml
  roles:
    - { role: backup }
