- hosts: backup-servers
  vars_files:
    - group_vars/secrets.yml
  roles: 
  - common
  - extra-storage
  - photo-backup

- hosts: common
  vars_files:
    - group_vars/secrets.yml
  roles:
    - { role: common }

- hosts: extra-storage
  roles:
    - { role: extra-storage }

- hosts: duckdns
  vars_files:
    - group_vars/secrets.yml
  roles:
    - { role: duckdns }

- hosts: photo-backup
  vars_files:
    - group_vars/secrets.yml
  roles:
    - { role: photo-backup }
