- hosts: backup-servers
  become: true
  vars_files:
    - group_vars/secrets.yml
  roles: 
  - common
  - extra-storage
  - photo-backup

- hosts: common
  become: true
  vars_files:
    - group_vars/secrets.yml
  roles:
    - { role: common }

- hosts: extra-storage
  become: true
  roles:
    - { role: extra-storage }

- hosts: duckdns
  become: true
  vars_files:
    - group_vars/secrets.yml
  roles:
    - { role: duckdns }

- hosts: photo-backup
  become: true
  vars_files:
    - group_vars/secrets.yml
  roles:
    - { role: photo-backup }
